wsdl: "https://speller.yandex.net/services/spellservice?WSDL"
url: "https://test-stand.gb.ru/gateway/login"
posts: "https://test-stand.gb.ru/api/posts"
username: userapi0
password: ab2dcf5f0d
title: 'New post'
description: 'New post for pytest in python'
content: 'New post for pytest in python'